### ISSUE TITLE
Add Mock context 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-lambda-test-utils#1]
No event emitters or promises. keep it simple...
see:
- http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html
- https://github.com/SamVerschueren/aws-lambda-mock-context/blob/master/index.js

**Comment by Jbarget** [comment]
can this be closed as well?

**Comment by Jbarget** [comment]
closing because already merged https://github.com/dwyl/aws-lambda-test-utils/pull/3
