### ISSUE TITLE
create a mock event helper

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aws-lambda-test-utils#2]
see: http://docs.aws.amazon.com/lambda/latest/dg/intro-core-components.html

**Comment by Jbarget** [comment]
@nelsonic isnt this already done here:

`var testEvent = mockEventCreator.createDynamoDBEvent();`

https://github.com/dwyl/aws-lambda-test-utils/blob/master/mockEvent.js

**Comment by nelsonic** [comment]
@Jbarget good point. closing. (_this issue should have been closed by the PR..._)
