### ISSUE TITLE
context.getRemainingTimeInMillis();

### ISSUE THREAD

**Issue by benjaminlees** [dwyl/aws-lambda-test-utils#5]
@nikhilaravi  the getRemainingTimeInMillis() method is missing from the mock context object, was this on purpose ?
If not I would be happy to add this with a test etc.

**Comment by nelsonic** [comment]
@benjaminlees I don't think it was omitted deliberately... feel free to add it in if you have time. :+1:

**Comment by benjaminlees** [comment]
@nelsonic i can add it tomorrow no probz :+1:

**Comment by iteles** [comment]
Amazing @benjaminlees, thank you!

**Comment by nikhilaravi** [comment]
@benjaminlees was omitted because we weren't using it in any of our lambda functions but it should definitely be added in!!  :+1:

**Comment by nelsonic** [comment]
Closing as this was implemented by Benji's PR. :+1:
